#docker-compose.override
name: myapp

#x-logging
x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  #database section
  
  #educationDB: mysql
  educationDB:
    container_name: educationDB
    environment:
      MYSQL_ROOT_PASSWORD: "admin@1234"
    restart: always
    volumes:
      - lw_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  
  #judge0Db: postgresql
  db:
    container_name: db
    env_file: judge0.conf
    <<: *default-logging
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - lw_judge0_data:/var/lib/postgresql/data
  
  #cacheDB: redis
  redis:
    container_name: redis
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always
    ports:
      - "6379:6379"

  #infrastructure section
  lw_elasticsearch:
    container_name: lw_elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=admin1234
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - lw_elasticsearch_data:/usr/share/elasticsearch/data
  
  lw_kibana:
    container_name: lw_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://lw_elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=admin1234
    depends_on:
      - lw_elasticsearch
    ports:
      - "5601:5601"
  
  lw_judge0Server:
    container_name: lw_judge0Server
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - redis
      - db
  
  lw_judge0Workers:
    container_name: lw_judge0Workers
    command: [ "./scripts/workers" ]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    depends_on:
      - redis
      - db

  #services api section
  lw.api:
    container_name: lw.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnectionString=Server=educationDB,Port=3306;Database=EducationDB;Uid=root;Pwd=admin@1234;"
      - "CacheSettings:ConnectionString=redis:6379"
      - "CacheSettings:Password=admin@1234"
      - "ElasticsearchSettings:Uri=http://lw_elasticsearch:9200"
      - "ElasticsearchSettings:DefaultIndex=defaultindex"
      - "ElasticsearchSettings:Username=elastic"
      - "ElasticsearchSettings:Password=admin1234"
      - "UrlBase:Judge0Url=http://lw_judge0Server:2358/"
    depends_on:
      - educationDB
      - lw_elasticsearch
      - lw_kibana
      - lw_judge0Server
      - lw_judge0Workers
      - db
      - redis
    ports:
      - "8000:80"
    restart: always