#docker-compose
name: myapp

services:
  educationDB:
    image: mysql:8.0.37
  
  redis:
    image: redis:7.2.4
  
  db:
    image: postgres:16.2
  
  #infrastructure section
  lw_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22

  lw_kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
  
  lw_judge0Server:
    image: judge0/judge0:1.13.1

  lw_judge0Workers:
    image: judge0/judge0:1.13.1

  #api section
  lw.api:
    image: ${DOCKER_REGISTRY-}lw-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: LW.API/Dockerfile

#network section
networks:
  default:
    name: lw_network_service
    driver: bridge

#vollumes section
volumes:
  lw_mysql_data:
    name: lw_mysql_data
  lw_elasticsearch_data:
    name: lw_elasticsearch_data
  lw_jaeger_data:
    name: lw_jaeger_data
  lw_judge0_data:
    name: lw_judge0_data