#docker-compose.override
name: myapp

services:
  #database section
  
  #educationDB: mysql
  educationDB:
    container_name: educationDB
    environment:
      MYSQL_ROOT_PASSWORD: "admin@1234"
    restart: always
    volumes:
      - lw_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  #cacheDB: redis
  cacheDB:
    container_name: cacheDB
    restart: always
    ports:
      - "6379:6379"

  #infrastructure section
  lw_elasticsearch:
    container_name: lw_elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=admin1234
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - lw_elasticsearch_data:/usr/share/elasticsearch/data
  
  lw_kibana:
    container_name: lw_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://lw_elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=admin1234
    depends_on:
      - lw_elasticsearch
    ports:
      - "5601:5601"

#  #services api section
#  lw.api:
#    container_name: lw.api
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://+:80
#      - "ConnectionStrings:DefaultConnectionString=Server=educationDB,Port=3306;Database=Database;Uid=root;Pwd=admin@1234;"
#    depends_on:
#      - educationDB
#    ports:
#      - "8000:80"
#    restart: always